apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: majutus
  template:
    metadata:
      labels:
        app: majutus
    spec:
      containers:
        - name: majutus
          image: us.gcr.io/electric-block-416308/majutus:v0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            runAsUser: 0 # Running as root user
