apiVersion: apps/v1
kind: Deployment
metadata:
  name: majutus-deployment
  labels:
    app: majutus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: majutus
  template:
    metadata:
      labels:
        app: majutus
    spec:
      containers:
        - name: majutus
          image: gcr.io/electric-block-416308/matis_front/majutus:v0.1
          ports:
            - containerPort: 80
